import { EVIDENCE } from '../components/EvidenceInfo';



export const ghostInfo = [
  { name: 'Demon', evidence: [EVIDENCE.FREEZINGTEMPS, EVIDENCE.GHOST_WRITING, EVIDENCE.SPIRIT_BOX], weakness: 'Asking a Demon Succeeful questions on the Ouija board does not lower sanity', strength: 'Demons will begin hunts more often', description: 'A Demon is one of the worst Ghosts you can encounter. It has been known to attack without a reason.' },
  { name: 'Spirit', evidence: [EVIDENCE.GHOST_WRITING, EVIDENCE.FINGERPRINTS, EVIDENCE.SPIRIT_BOX], weakness: 'Smudge Sticks will stop it attacking for 180 seconds instead of 90', strength: 'None', description: 'A Spirit is the most common Ghost you will come across however it is still very powerful and dangerous. They are usually discovered at one of their hunting grounds after an unexplained death.' },
  { name: 'Phantom', evidence: [EVIDENCE.EMF_LEVEL_5, EVIDENCE.FREEZINGTEMPS, EVIDENCE.GHOST_ORBS], weakness: 'Taking a photo of the Phantom will make it temporarily disappear. This, however, will not stop a Hunt.', strength: 'Looking at a Phantom will considerably drop your Sanity. This refers to any visible manifestations of the Phantom, including during a Hunt', description: 'A Phantom is a Ghost that can possess the living, most commonly summoned by a Ouija Board. It also induces fear into those around it.' },
  { name: 'Banshee', evidence: [EVIDENCE.EMF_LEVEL_5, EVIDENCE.FINGERPRINTS, EVIDENCE.FREEZINGTEMPS], weakness: 'Banshees fear the Crucifix, which boosts the Hunt-stopping range of one from 3 meters to 5 meters against it', strength: 'A Banshee will focus on one player at a time until it kills them or the player leaves the building', description: 'A Banshee is a natural hunter and will attack anything. It has been known to stalk its prey one at a time until making its kill.' },
  { name: 'Mare', evidence: [EVIDENCE.FREEZINGTEMPS, EVIDENCE.GHOST_ORBS, EVIDENCE.SPIRIT_BOX], weakness: 'Turning the lights on will lower its chance to attack', strength: 'Increased chance to attack in the dark. As such, it will do what it can to achieve this, such as turning off lights and tripping the fuse box', description: 'A Mare is the source of all nightmares, making it most powerful in the dark' },
  { name: 'Yurei', evidence: [EVIDENCE.FREEZINGTEMPS, EVIDENCE.GHOST_ORBS, EVIDENCE.GHOST_WRITING], weakness: 'Using Smudge Sticks on the Yurei will cause it to not wander around the location for ~90 seconds', strength: 'Yurei have been known to have a stronger effect on peoples Sanity during a manifestation', description: 'A Yurei is a Ghost that has returned to the physical world, usually for the purpose of revenge or hatred.' },
  { name: 'Wraith', evidence: [EVIDENCE.FINGERPRINTS, EVIDENCE.FREEZINGTEMPS, EVIDENCE.SPIRIT_BOX], weakness: 'Wraiths have a toxic reaction to Salt. If a Wraith comes into contact with a pile of salt, Ghost Activity will significantly increase', strength: 'Wraiths almost never touch the ground, footprint sounds from a wraith will be rare to non-existent.', description: 'A Wraith is one of the most dangerous Ghosts you will find. It is also the only known ghost that has the ability of flight and has sometimes been known to travel through walls.' },
  { name: 'Jinn', evidence: [EVIDENCE.EMF_LEVEL_5, EVIDENCE.GHOST_ORBS, EVIDENCE.SPIRIT_BOX], weakness: 'Turning off the power source will prevent the Jinn from using its ability', strength: 'A Jinn will travel at a faster speed if its victim is far away', description: 'A Jinn is a territorial Ghost that will attack when threatened. It also has been known to travel at significant speed.' },
  { name: 'Shade', evidence: [EVIDENCE.EMF_LEVEL_5, EVIDENCE.GHOST_ORBS, EVIDENCE.GHOST_WRITING], weakness: 'A Shade will rarely start a Hunt when players are grouped together', strength: 'As a shy ghost, a Shade will rarely perform actions in the presence of two or more people, making it harder to detect', description: 'A Shade is known to be a Shy Ghost. There is evidence that a Shade will stop all paranormal activity if there are multiple people nearby.' },
  { name: 'Oni', evidence: [EVIDENCE.EMF_LEVEL_5, EVIDENCE.GHOST_WRITING, EVIDENCE.SPIRIT_BOX], weakness: 'Being more active will make the Oni easier to find and identify', strength: 'Oni are more active when people are nearby and have been seen moving objects at great speed', description: 'Onis are a cousin to the Demon and possess extreme strength. There have been rumors that they become more active around their prey.' },
  { name: 'Revenant', evidence: [EVIDENCE.EMF_LEVEL_5, EVIDENCE.FINGERPRINTS, EVIDENCE.GHOST_WRITING], weakness: 'Hiding from the Revenant will cause it to move very slowly', strength: 'A Revenant will travel at a significantly faster speed when hunting a victim. Additionally, the Revenant can freely switch whoever it is targeting during a Hunt', description: 'A Revenant is a slow but violent Ghost that will attack indiscriminantly. It has been rumored to travel at a significantly high speed when hunting.' },
  { name: 'Poltergeist', evidence: [EVIDENCE.GHOST_ORBS, EVIDENCE.FINGERPRINTS, EVIDENCE.SPIRIT_BOX], weakness: 'A Poltergeist is almost ineffective in an empty room', strength: 'A Poltergeist is capable of influencing more objects at once than any other Ghosts, and is capable of shutting multiple doors at once', description: 'One of the most famous Ghosts, a Poltergeist, also known as a noisy ghost can manipulate objects around it to spread fear into its victims.' }
];